import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
  preferred-width:100%;
  preferred-height:100%;
  in-out property <string> text: "Nothin'";
  title: "Church Manager";
  callback request-query();
  VerticalBox {
    Text {
      text: "Query: \{root.text}";
    }

    Button {
      text: "Select All Query";
      clicked => {
        root.request-query();
      }
    }
  }
}
