import { Button, VerticalBox, StandardListView } from "std-widgets.slint";
import {Palette, Callbacks} from "globalVariables.slint";


component SidebarButton inherits Rectangle {
    in-out property text <=> txt.text;
    in-out property <bool> hovered: touch.has-hover;
    callback clicked <=> touch.clicked;
    background: touch.has-hover ? Palette.primary : Palette.secondary;
    height: 4rem;
    padding: 0.5rem;
    border-radius: 1rem;
    txt := Text {
        x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0);
    color: Palette.text;
    }

    touch := TouchArea { }
}

component Sidebar {
    in property <int> buttons: 4;
    VerticalBox {
        alignment: start;
        spacing: 0.5rem;
        height: 100%;
        width: parent.width;
        for i in buttons: SidebarButton {
            width: self.hovered ? 0.9*parent.width : 0.8*parent.width;
            x: 0px;
            text: "Button " + (i + 1);
            clicked => {
                Callbacks.switchDarkMode();
            }
        }
    }
}

export component MainWindow inherits Window {
    preferred-height: 1080px;
    preferred-width: 1920px;
    min-height: 600px;
    min-width: 1080px;
    background: Palette.background;
    in property <string> text: "Fullscreen by default";
    in-out property <bool> DarkMode <=> Palette.DarkMode;
    in property <[string]> elements: [];
    title: "Church Manager";
    callback fullScreen <=> Callbacks.fullscreen;
    callback selectAll <=> Callbacks.selectAll;
    callback switchDarkMode <=> Callbacks.switchDarkMode;
    callback updatePerson();
    HorizontalLayout {
        width: 100%;
        height: 100%;
        alignment: start;
        Sidebar { 
        width: 50px;
      }

        StandardListView {
            width: 150px;
            height: 150px;
            model: [];
        }

        Text {
            width: parent.width / 2 - 50px;
            height: 100%;
            vertical-alignment: center;
      color: Palette.text;
            text: text;
        }

        VerticalBox {
            width: parent.width / 2 - 50px;
            height: 100%;
            alignment: center;
            Button {
                height: 100px;
                width: 200px;

                text: "Query";
                clicked => {
                    selectAll();
                }
            }

            Button {
                height: 100px;
                width: 200px;

                text: "Update";
                clicked => {
                    updatePerson();
                }
            }
        }
    }
}
